# Generated by Django 3.2 on 2021-04-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_data_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumn',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='csv_data_generator.schema'),
        ),
    ]
