# Generated by Django 3.2 on 2021-04-11 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csv_data_generator', '0002_alter_schemacolumn_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 11, 11, 46, 13, 655674, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schema',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
