# Generated by Django 3.2 on 2021-04-11 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_data_generator', '0003_auto_20210411_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaDataSetCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('ready', 'Ready'), ('pending', 'Pending')], max_length=50)),
                ('link', models.FileField(upload_to='datasets/')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sets_csv', to='csv_data_generator.schema')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
