# Generated by Django 3.2 on 2021-04-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_data_generator', '0004_schemadatasetcsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemadatasetcsv',
            name='link',
            field=models.FileField(default=None, null=True, upload_to='datasets/'),
        ),
    ]
