# Generated by Django 3.2 on 2021-04-11 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csv_data_generator', '0005_alter_schemadatasetcsv_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to=settings.AUTH_USER_MODEL),
        ),
    ]
